image: Visual Studio 2022

configuration:
  - Release
  - Debug

platform:
  - x64
  - Win32

environment:
  CMAKE_OPTIONS: "-A \"%platform%\" -DCMAKE_BUILD_TYPE=\"%configuration%\" -DUSE_STATIC_RUNTIME=ON"
  # VS VERSION IN CMAKE STYLE
  matrix:
    - VSVERSION: "17 2022"
    - VSVERSION: "16 2019"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - VSVERSION: "15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      
matrix:
  exclude:
    - VSVERSION: "17 2022"
      platform: Win32

init:
  - cmake --version
  - msbuild /version

before_build:
  - set VSVERSIONSHORT=%VSVERSION:~3,4%
  - if "%APPVEYOR_REPO_TAG_NAME%"=="" ( set "APPVEYOR_REPO_TAG_NAME=dev-%VSVERSIONSHORT%-%platform%-%configuration%" )
  - mkdir build
  - cd build
  - cmake -G "Visual Studio %VSVERSION%" -DCPACK_PACKAGE_VERSION="%APPVEYOR_REPO_TAG_NAME%" %CMAKE_OPTIONS% ..

build_script:
  - cmake --build . --config %configuration%

after_build:
  - cmake --build . --target package

artifacts:
  - path: build/win_flex_bison*.zip
