image: Visual Studio 2019

configuration:
  - Release
  - Debug

platform:
  - x64
  - Win32

environment:
  CMAKE_OPTIONS: "-A \"%platform%\" -DCMAKE_BUILD_TYPE=\"%configuration%\" -DUSE_STATIC_RUNTIME=ON"
  # VS VERSION IN CMAKE STYLE
  matrix:
    - VSVERSION: "16 2019"
    - VSVERSION: "15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - VSVERSION: "14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

init:
  - cmake --version
  - msbuild /version

before_build:
  - set VSVERSIONSHORT=%VSVERSION:~3,4%
  - if "%APPVEYOR_REPO_TAG_NAME%"=="" ( set "APPVEYOR_REPO_TAG_NAME=dev-%VSVERSIONSHORT%-%platform%-%configuration%" )
  - mkdir build
  - cd build
  - cmake -G "Visual Studio %VSVERSION%" -DCPACK_PACKAGE_VERSION="%APPVEYOR_REPO_TAG_NAME%" %CMAKE_OPTIONS%  ..

build:
  project: "build\\winflexbison.sln"
  parallel: false

after_build:
  - cmake --build . --target package

artifacts:
  - path: build/win_flex_bison*.zip
